# Docker compose for development purposes only
version: '3.8'
services:
  shiori:
    image: peppershade/shiori:latest
    # Set user using the same UID and GID as the host user
    user: 0:0
    container_name: shiori
    environment:
    # Set the secret key to secure the HTTP API
      - SHIORI_HTTP_SECRET_KEY=your_secret_key_here
    ports:
      - "18080:8080"
    volumes:
    # Mount the data directory to persist data
      - ./data:/shiori-data
    restart: always